[Potato DeviceProfile]
Cvars=r.Mobile.HighQualityMaterial=0  ;1 for better graphics
Cvars=r.Android.DisableVulkanSupport=0  ;change to 1 if you have vulkan rendering problems
Cvars=wp.Runtime.LoadingRangeScale=0.80
;sg groups
CVars=sg.ViewDistanceQuality=0
CVars=sg.AntiAliasingQuality=0
CVars=sg.ShadowQuality=0
CVars=sg.PostProcessQuality=0
CVars=sg.TextureQuality=0
CVars=sg.EffectsQuality=0
CVars=sg.FoliageQuality=0
CVars=sg.ShadingQuality=0
CVars=wp.Runtime.LoadingRangeScale=0.20
CVars=wp.Runtime.PlannedLoadingRangeScale=0.50
CVars=a.URO.Enable=1
CVars=a.URO.ForceAnimRate=3 ;set to 2 if chars feel weird for u
CVars=a.URO.ForceInterpolation=1

[Android_Default DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_TegraK1 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Mali_G61x DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Mali_Immortalis DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Mali_Gx_Ultra DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Mali_G92x DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_MTK_6991 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_IMG_BXM DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Mali_G57_MC2 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Mali_G720 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Adreno_7xx DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Adreno740 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Adreno_6xx DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Adreno825 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Adreno840 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Adreno830 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Adreno_8xx DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Adreno810 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Xclipse9xx DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Xclipse940 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Adreno7xx_Low DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Xclipse930 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Xclipse5xx DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Mali_G68 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Tensor_G4 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000

[Android_Tensor_G3 DeviceProfile]
BaseProfileName=Potato
DeviceScore=5000